apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
    target: auth
spec:
  selector:
    matchLabels:
      target: auth
  replicas: 1
  template:
    metadata:
      labels:
        target: auth
    spec:
      containers:
        - name: container
          image: uac
          imagePullPolicy: IfNotPresent
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: MONGO_URL
              value: mongodb://mongo-service:27017/
          ports:
            - containerPort: 4000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
