apiVersion: apps/v1
kind: Deployment
metadata:
  name: classifier
  labels:
    app: classifier
    target: classifier
spec:
  selector:
    matchLabels:
      target: classifier
  replicas: 1
  template:
    metadata:
      labels:
        target: classifier
    spec:
      containers:
        - name: classifier
          image: classifier
          imagePullPolicy: Always
          env:
            - name: GET_HOSTS_FROM
              value: dns
          command: ["python3","./bin_class.py"]
          ports:
            - containerPort: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always
