apiVersion: apps/v1
kind: Deployment
metadata:
  name: classifier
  labels:
    app: classifier
    target: classifier
spec:
  selector:
    matchLabels:
      target: classifier
  replicas: 1
  template:
    metadata:
      labels:
        target: classifier
    spec:
      containers:
        - name: classifier
          image: classifier
          imagePullPolicy: IfNotPresent
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: MONGO_URL
              value: mongodb://mongo-service:27017/
          ports:
            - containerPort: 7001
      dnsPolicy: ClusterFirst
      restartPolicy: Always
