apiVersion: apps/v1
kind: Deployment
metadata:
  name: eda
  labels:
    app: eda
    target: eda
spec:
  selector:
    matchLabels:
      target: eda
  replicas: 1
  template:
    metadata:
      labels:
        target: eda
    spec:
      containers:
        - name: container
          image: eda
          imagePullPolicy: IfNotPresent
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: MONGO_URL
              value: mongodb://mongo-service:27017/
          ports:
            - containerPort: 6001
      dnsPolicy: ClusterFirst
      restartPolicy: Always
