apiVersion: apps/v1
kind: Deployment
metadata:
  name: eda
  labels:
    app: eda
    target: eda
spec:
  selector:
    matchLabels:
      target: eda
  replicas: 1
  template:
    metadata:
      labels:
        target: eda
    spec:
      containers:
        - name: container
          image: eda
          imagePullPolicy: Always
          env:
            - name: GET_HOSTS_FROM
              value: dns
          command: ["python3","./eda.py"]
          ports:
            - containerPort: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always
