apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-data
  labels:
    app: mongo-data
    target: mongo-data
spec:
  selector:
    matchLabels:
      target: mongo-data
  replicas: 1
  template:
    metadata:
      labels:
        target: mongo-data
    spec:
      containers:
        - name: container
          image: mongo
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
            - containerPort: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always
