---

apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  ports:
  - name: web
    port: 4000
    targetPort: 4000
  selector:
    target: auth
  type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  name: classifier
spec:
  ports:
  - name: web
    port: 7001
    targetPort: 7001
  selector:
    target: classifier
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  ports:
  - name: normal
    port: 27017
    targetPort: 27017
  selector:
    target: mongo-data
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: eda
spec:
  ports:
  - name: web
    port: 6001
    targetPort: 6001
  selector:
    target: eda
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  ports:
  - name: web
    port: 5000
    targetPort: 5000
  selector:
    target: user
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  ports:
  - name: web
    port: 80
    targetPort: 80
  selector:
    target: ui
  type: LoadBalancer



