apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui
    target: ui
spec:
  selector:
    matchLabels:
      target: ui
  replicas: 1
  template:
    metadata:
      labels:
        target: ui
    spec:
      containers:
        - name: container
          image: frontend
          imagePullPolicy: IfNotPresent
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: MONGO_URL
              value: mongodb://mongo-service:27017/
          ports:
            - containerPort: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always
