apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
    target: user
spec:
  selector:
    matchLabels:
      target: user
  replicas: 1
  template:
    metadata:
      labels:
        target: user
    spec:
      containers:
        - name: container
          image: user
          imagePullPolicy: IfNotPresent
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: MONGO_URL
              value: mongodb://mongo-service:27017/
          ports:
            - containerPort: 5000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
